#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          0
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# workspaces settings
# yabai -m space 1 --label main
# yabai -m space 2 --label browser
# yabai -m space 3 --label console
# yabai -m space 4 --label chat
# yabai -m space 5 --label mail
# yabai -m space 6 --label aux-1
# yabai -m space 7 --label aux-2
# yabai -m space 8 --label aux-3
# yabai -m space 9 --label aux-4
# yabai -m space 10 --label aux-5
# yabai -m space 11 --label musique
# yabai -m space 12 --label monitoring

# general space settings
yabai -m config layout                       bsp
# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^AppGate" manage=off
# yabai -m config top_padding                  0
# yabai -m config bottom_padding               0
# yabai -m config left_padding                 0
# yabai -m config right_padding                0
# yabai -m config window_gap                   0

echo "yabai configuration loaded.."
