#!/usr/bin/python

import os

stateFilename = "/tmp/batteryBlocketState"

try:
    with open(stateFilename,"a+") as f:
        fileout = f.realine().split()
        if len(fileout):
            if fileout[0] == "":
                old_status = "NotAlerted"
            else :
                old_status = fileout[0]
        else:
            f.write("NotAlerted")
        f.close()
except:
    old_status = "NotAlerted"



bash_command = "acpi -b | grep Battery"
bash_command_bis = "acpi -i | grep capacity"
def onlyDigit(string) :
    return ''.join(c for c in string if c.isdigit())

rawOutput = os.popen(bash_command).read().split('\n')
percent = dict()
charging = 0
#print(rawOutput)
for line in rawOutput:
    if line != '':
        line=line.split(" ")
        percent[line[1][0]] = int( onlyDigit( line[3] ))
        if line[2][:-1] == "Charging":
            charging = 1
        elif line[2][:-1] == "Discharging":
            charging = -1


rawOutputCapacity = os.popen(bash_command_bis).read().split('\n')
capacity = dict()

#print(percent)
for line in rawOutputCapacity:
    if line != '':
        line = line.split(" ")
        capacity[line[1][0]] = int( onlyDigit( line[4] ) )

truePercentage = 0
#print(capacity)

for i in range(len(percent)):
    modifier = capacity[str( i )]/sum(capacity.values())
    truePercentage += percent[str(i)]*modifier
if ( charging ) == 1 :
    status = " CHR"
elif ( charging ) == -1:
    status = " DIS"
else :
    status = " ---"

print(str(int(truePercentage)) + "%" + status)
print(str(int(truePercentage)) + "%" + status)

if charging == -1 :
    if (int(truePercentage) < 20) :
        print("#FF0000\n")
    elif (int(truePercentage) < 40) :
        print("#FFAE00\n")
    elif (int(truePercentage) < 60) :
        print("#FFF600\n")
    elif (int(truePercentage) < 99) :
        print("#88FF00\n")

    if (int(truePercentage) < 5) :
        if (old_status == "NotAlerted"):
            os.popen("notify-send \"Battery Low\" \"Please plug your computer\"")
            command = "echo Alerted > " + stateFilename
            os.popen(command)
        exit(33);
else :
    if (old_status == "Alerted"):
        command = "echo NotAlerted > " + stateFilename
        os.popen(command)
    print("#8800FF\n")
