#!/usr/bin/python

import os
from time import sleep

sleep(0.1)
BLOCK_INSTANCE = os.getenv("BLOCK_INSTANCE", "spotify")

metadata = []
player_arg=""
if (BLOCK_INSTANCE) :
    player_arg = "--player="+BLOCK_INSTANCE

# if ($ENV{'BLOCK_BUTTON'} == 1) {
#     system("playerctl $player_arg previous");
# } elsif ($ENV{'BLOCK_BUTTON'} == 2) {
#     system("playerctl $player_arg play-pause");
# } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
#     system("playerctl $player_arg next");
# }
output = os.popen('playerctl metadata '+ player_arg+ ' --format "{{ status }} : {{ artist }} - {{ title }}"').read()
# if (len(output))
print(output)

