#!/usr/bin/python

import os

BLOCK_INSTANCE = os.getenv("BLOCK_INSTANCE", "spotify")

metadata = []
player_arg=""
if (BLOCK_INSTANCE) :
    player_arg = "--player="+BLOCK_INSTANCE

# if ($ENV{'BLOCK_BUTTON'} == 1) {
#     system("playerctl $player_arg previous");
# } elsif ($ENV{'BLOCK_BUTTON'} == 2) {
#     system("playerctl $player_arg play-pause");
# } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
#     system("playerctl $player_arg next");
# }

artist = os.popen("playerctl " +player_arg+ " metadata artist").read().strip('\n')
title = os.popen("playerctl " +player_arg+ " metadata title").read()
print(artist + " - " + title)

